### ISSUE TITLE
Convert JavaScript code to TypeScript

### ISSUE THREAD

**Issue by qu8n** [qu8n/focusbeacon#11]
All Pull Requests are welcome for this work, whether it is JS-TS conversion of a single file or multiple files. Because TS is just a superset of JS, we don't need to convert all the files at once. 

The first step would include the initial setup and configurations, such as installing TS and adding the config file `tsconfig.json`. If you have any questions, comment below and I'll respond within 24 hours.

Recommended reading:
[https://www.sitepoint.com/how-to-migrate-a-react-app-to-typescript](https://www.sitepoint.com/how-to-migrate-a-react-app-to-typescript)

**Comment by FaizanMuhammadSE** [comment]
@qu8n, you want to configure typescript in your project, right?

**Comment by qu8n** [comment]
@FaizanMuhammadSE Yes. This project is all in JS at the moment. The first step to converting JS code to TS would include the initial setup and configurations, such as installing TS and adding the config file `tsconfig.json`. Let me know if you have any other questions!
