### ISSUE TITLE
Refactor the `Modal` component to be more generic

### ISSUE THREAD

**Issue by qu8n** [qu8n/focusbeacon#22]
The `Modal` component is used to display a popup modal when users click on "About" or "Privacy" on the navbar. 

**Current state:**
```js
// _app.js
...
<NavBar
  setShowAboutModal={setShowAboutModal}
  setShowPrivacyModal={setShowPrivacyModal}
/>

{(showAboutModal || showPrivacyModal) && (
  <Modal
    modalType={showAboutModal ? "about" : "privacy"}
    setShowAboutModal={setShowAboutModal}
    setShowPrivacyModal={setShowPrivacyModal}
  />
)}
...
```
The mechanism to show either the About or Privacy's content is not generic. There are two setState methods for each content.

**Ideal state:**
There is a generic `Modal` component that receives two props: (1) `setOpen` that dictates whether the modal should open, and (2) `textContent` that includes the texts inside the modal.

**Comment by mahdiQaempanah** [comment]
I can work on it, can you assign it to me?

**Comment by qu8n** [comment]
@mahdiQaempanah Done. Let me know if you have any questions along the way 🙂

**Comment by mahdiQaempanah** [comment]
I sent the pull request.
[https://github.com/qu8n/focusbeacon/pull/23](url)
